### ISSUE TITLE
SyncOrg does empty commits when I open it

### ISSUE THREAD

**Issue by fishman** [wizmer/syncorg#16]
I have the same as the guy in this picture

![Commit changes to all files](http://i.imgur.com/cfMJNG5.png)

**Comment by chasecaleb** [comment]
I can confirm this is an issue as well. I don't see any built in debug logging via the UI to submit, though.

**Comment by ayyess** [comment]
This could temporarily be fixed with something like

``` diff
diff --git i/SyncOrg/src/main/java/com/coste/syncorg/synchronizers/JGitWrapper.java w/SyncOrg/src/main/java/com/coste/syncorg/synchronizers/JGitWrapper.java
index 1b8f83a..eb91931 100644
--- i/SyncOrg/src/main/java/com/coste/syncorg/synchronizers/JGitWrapper.java
+++ w/SyncOrg/src/main/java/com/coste/syncorg/synchronizers/JGitWrapper.java
@@ -430,6 +430,9 @@ public class JGitWrapper {
             Git git = null;
             try {
                 git = Git.open(repoDir);
+                if (git.status().call().isClean()) {
+                    return null;
+                }
                 // Stage all changed files, omitting new files, and commit with one command

 //                org.eclipse.jgit.api.Status status = git.status().call();
```

**Comment by barryWarnock** [comment]
This is still a problem on the android app

**Comment by colonelpanic8** [comment]
Why was this closed. It seems like people are still having this issue?

**Comment by wizmer** [comment]
I fixed it yesterday.

Le mer. 25 janv. 2017 08:40, Ivan Malison <notifications@github.com> a
écrit :
